Task_5


Point_1


In [9]:
import numpy as np
matrix = np.zeros((5,5), dtype=int)
matrix[0,:] = 1
matrix[-1,:] = 1
matrix[:,0] = 1
matrix[:,-1] = 1
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Point_2


In [15]:
import numpy as np
matrix = np.full((5,5),3)
np.fill_diagonal(np.fliplr(matrix),2)
np.fill_diagonal(matrix,1)
print(matrix)

[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 1 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]


Point_3


In [19]:
import numpy as np
x=np.array([[5,3]
            ,[3,-6]])
R=np.array([20,10])
solution =np.linalg.solve(x,R)
print(solution)

[3.84615385 0.25641026]


Point_4

In [22]:
import numpy as np
first=np.array(["ahmed","elsayed","ahmed"])
second=np.array(["engineer","doctor","teacher"])
result=np.vstack((first,second))
print(result)

[['ahmed' 'elsayed' 'ahmed']
 ['engineer' 'doctor' 'teacher']]
