In [5]:
import numpy as np
x1 = np.array([[1,1,1,1,1],
              [1,0,0,0,1],
              [1,0,0,0,1],
              [1,0,0,0,1],
              [1,1,1,1,1]])

x2 = np.array([[1,3,3,3,2],
               [3,1,3,2,3],
               [3,3,2,3,3,],
               [3,2,3,1,3],
               [2,3,3,3,1]])


print(x1)
print("=============================")
print(x2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]
